name: pctsp
channels:
  - conda-forge
  - http://conda.anaconda.org/gurobi
  - scipopt
  - defaults
dependencies:
  - boost>=1.84.0
  - python>=3.12.0
  - cmake>=3.27.0
  - scip>=9.0.0
  - pyscipopt>=5.0.0
  - pip:
    - -r file:requirements.txt