
name: Docker build
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SETUPTOOLS_SCM_PRETEND_VERSION_FOR_PCTSP: ${{ github.event.release.tag_name }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    # - name: Docker build SCIP
    #   run: docker build -f scip.dockerfile -t patrickohara/scip:latest .
    # - name: Docker push SCIP
    #   run: docker push patrickohara/scip:latest
    - name: Docker build PCTSP
      run: DOCKER_BUILDKIT=1 docker build -f Dockerfile -t patrickohara/pctsp:latest .
    - name: Docker push
      run: docker push patrickohara/pctsp:latest
