
name: Docker build
on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2  
    - name: Create tag artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{github.ref_name}}
        path: Release
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    # - name: Docker build SCIP
    #   run: docker build -f scip.dockerfile -t patrickohara/scip:latest .
    # - name: Docker push SCIP
    #   run: docker push patrickohara/scip:latest
    - name: Docker build PCTSP
      run: docker build --build-arg PCTSP_VERSION=${{ github.event.release.tag_name }} -f Dockerfile -t patrickohara/pctsp:latest .
    - name: Docker push
      run: docker push patrickohara/pctsp:latest
