
name: Docker build
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Docker build
      run: |
        docker build -f scip.dockerfile -t patrickohara/scip:latest .
        docker build -f Dockerfile -t patrickohara/pctsp:latest .

    - name: Docker push
      run: |
        docker push patrickohara/scip:latest
        docker push patrickohara/pctsp:latest
