name: Python package

on: [push]

jobs:

  test-cpp:
    runs-on: ubuntu-latest
    container: patrickohara/scip:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install scikit-build ninja
    - name: Build
      run: |
        mkdir build
        cd build
        cmake -GNinja ..
        cmake --build .
    - name: Test
      run: |
        mkdir .logs
        ./build/tests/test_pctsp

  test-python:
    runs-on: ubuntu-latest
    container: patrickohara/scip:latest
    env:
      OPLIB_ROOT: ../OPLib
      TSPLIB_ROOT: ../tsplib95/archives/problems/tsp
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install development dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
    - name: Install pctsp
      run: pip3 install .
    - name: Download test data
      run: |
        git clone https://github.com/bcamath-ds/OPLib.git ${OPLIB_ROOT}
        git clone https://github.com/rhgrant10/tsplib95.git ${TSPLIB95_ROOT}
    - name: Test pctsp
      run: pytest tests
    - name: Lint
      run: |
        pylint pctsp/*
        pylint tests/*
        mypy pctsp
        black --check */
